FIX CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,6 +46,29 @@ jobs:
           echo "MAILER_DSN=smtp://localhost:1025" >> .env
           echo "APP_ENV=prod" >> .env
       -
+        name: Verify .env file creation
+        run: |
+          if [ -f .env ]; then
+            echo ".env file is present."
+            cat .env | head -n 10
+          else
+            echo "Error: .env file is missing!" && exit 1
+          fi
+      -
+        name: Build Docker images
+        uses: docker/bake-action@v6
+        with:
+          pull: true
+          load: true
+          files: |
+            compose.yaml
+            compose.prod.yaml
+
+          set: |
+            *.cache-from=type=gha,scope=${{github.ref}}
+            *.cache-from=type=gha,scope=refs/heads/main
+            *.cache-to=type=gha,scope=${{github.ref}},mode=max
+      -
         name: Start services
         run: docker compose up --no-build
       - 
